#!/usr/bin/env bash

#pm2 start init.js --name=api --log-date-format=YYYY-MM-DD HH:mm Z -- --module=api
#pm2 start init.js --name=remoteShare --log-date-format=YYYY-MM-DD HH:mm Z -- --module=remoteShare
#pm2 start init.js --name=pool --log-date-format=YYYY-MM-DD HH:mm Z -- --module=pool
#pm2 start init.js --name=blockManager --log-date-format=YYYY-MM-DD HH:mm Z -- --module=blockManager
#pm2 start init.js --name=payments --log-date-format=YYYY-MM-DD HH:mm Z -- --module=payments
#pm2 start init.js --name=worker --log-date-format=YYYY-MM-DD HH:mm Z -- --module=worker
#pm2 start init.js --name=longRunner --log-date-format=YYYY-MM-DD HH:mm Z -- --module=longRunner

pm2 start /root/electronero/build/release/bin/electronero-wallet-rpc -- --rpc-bind-port 12092 --password-file ~/1/etn-wallet/wallet_pass --wallet-file ~/1/etn-wallet/etnx-pool --disable-rpc-login --trusted-daemon

pm2 list
cd ~/nodejs-pool/
pm2 start init.js --name=blockManager --log-date-format="YYYY-MM-DD HH:mm Z"  -- --module=blockManager
pm2 start init.js --name=worker --log-date-format="YYYY-MM-DD HH:mm Z" -- --module=worker
pm2 start init.js --name=payments --log-date-format="YYYY-MM-DD HH:mm Z" -- --module=payments
pm2 start init.js --name=remoteShare --log-date-format="YYYY-MM-DD HH:mm Z" -- --module=remoteShare
pm2 start init.js --name=longRunner --log-date-format="YYYY-MM-DD HH:mm Z" -- --module=longRunner
pm2 start init.js --name=pool --log-date-format="YYYY-MM-DD HH:mm Z" -- --module=pool
#pm2 restart api
pm2 start init.js --name=api --log-date-format="YYYY-MM-DD HH:mm Z" -- --module=api

#pm2 restart api

pm2 list
