#!/usr/bin/env bash


gnome-terminal -- /root/electroneropulse/build/release/bin/pulsed --block-sync-size 100 --fast-block-sync 1 --seed-node 206.189.20.68:20389 --seed-node 104.236.175.63:20389 --seed-node 174.138.15.35:20389 --seed-node 46.101.40.29:20389 --seed-node 107.170.236.49:20389 --seed-node 138.68.192.102:20389 --seed-node 165.227.189.226:20389 --seed-node 45.55.120.174:20389

cd /root/electronero-pool
 ./nvm1 current
./nvm1 use 8.11.3
npm update

cd /root/poolui

gnome-terminal -- npm start

cd /root/electronero-pool

pm2 start /root/electroneropulse/build/release/bin/pulse-wallet-rpc -- --rpc-bind-port 20394 --password-file ~/1/etn-wallet/wallet_pass --wallet-file ~/1/etn-wallet/etnx-pool --disable-rpc-login --trusted-daemon

./api-run
# gnome-terminal -- /root/electronero/build/release/bin/electronero-wallet-rpc --rpc-bind-port 12092 --password-file ~/1/etn-wallet/wallet_pass --wallet-file ~/1/etn-wallet/etnx-pool --disable-rpc-login --trusted-daemon
#pm2 start init.js --name=api --log-date-format=YYYY-MM-DD HH:mm Z -- --module=api
#pm2 start init.js --name=remoteShare --log-date-format=YYYY-MM-DD HH:mm Z -- --module=remoteShare
#pm2 start init.js --name=pool --log-date-format=YYYY-MM-DD HH:mm Z -- --module=pool
#pm2 start init.js --name=blockManager --log-date-format=YYYY-MM-DD HH:mm Z -- --module=blockManager
#pm2 start init.js --name=payments --log-date-format=YYYY-MM-DD HH:mm Z -- --module=payments
#pm2 start init.js --name=worker --log-date-format=YYYY-MM-DD HH:mm Z -- --module=worker
#pm2 start init.js --name=longRunner --log-date-format=YYYY-MM-DD HH:mm Z -- --module=longRunner
cd /root/electronero-pool/

#pm2 start /root/electroneropulse/build/release/bin/pulsed -x -- --block-sync-size 100 --fast-block-sync 1 --seed-node 206.189.20.68:20389 --seed-node 104.236.175.63:20389 --seed-node 174.138.15.35:20389 --seed-node 46.101.40.29:20389 --seed-node 107.170.236.49:20389 --seed-node 138.68.192.102:20389 --seed-node 165.227.189.226:20389 --seed-node 45.55.120.174:20389
sleep 60
#sleep 300
killall node
sleep 30
killall node
sleep 30
killall node
sleep 3


cd /root/electronero-pool
 ./nvm1 alias default 8.11.3
 ./nvm1 current

 ./nvm1 use 8.11.3
# Xeon 4.3G + ssd disk + 32+ DDR4 = 30 seconds
npm update

pm2 list

pm2 start /root/electroneropulse/build/release/bin/pulse-wallet-rpc -- --rpc-bind-port 20394 --password-file ~/1/etn-wallet/wallet_pass --wallet-file ~/1/etn-wallet/etnx-pool --disable-rpc-login --trusted-daemon
pm2 list
sleep 60
pm2 list
pm2 start init.js --name=api --log-date-format="YYYY-MM-DD HH:mm Z" -- --module=api
sleep 15
pm2 start init.js --name=blockManager --log-date-format="YYYY-MM-DD HH:mm Z"  -- --module=blockManager
pm2 start init.js --name=altblockManager --log-date-format="YYYY-MM-DD HH:mm Z"  -- --module=blockManager
pm2 start init.js --name=worker --log-date-format="YYYY-MM-DD HH:mm Z" -- --module=worker
pm2 start init.js --name=payments --log-date-format="YYYY-MM-DD HH:mm Z" -- --module=payments
pm2 start init.js --name=remoteShare --log-date-format="YYYY-MM-DD HH:mm Z" -- --module=remoteShare
pm2 start init.js --name=longRunner --log-date-format="YYYY-MM-DD HH:mm Z" -- --module=longRunner
pm2 start init.js --name=pool --log-date-format="YYYY-MM-DD HH:mm Z" -- --module=pool
#pm2 restart api


pm2 restart api
sleep 5

cd /root/poolui

gnome-terminal -- npm start

cd /root/electronero-pool/

# see version node , bignum, cryptonote util core (bignum won't start after re boot?)
gnome-terminal -- pm2 monit

 ./nvm1 alias default 8.11.3
 ./nvm1 current

LIMIT=500

for ((a=1; a <= $LIMIT ; a++))
 do
 echo $ARG
pm2 list
sleep 360

#sleep 5
 done
gnome-terminal