#!/usr/bin/env bash

# /root/masari/build/release/bin/masari-wallet-rpc --rpc-bind-port 38084 --password-file ~/1/masari/wallet_pass --wallet-file ~/1/masari/pool --disable-rpc-login --trusted-daemon
pm2 start /root/masari/build/release/bin/masari-wallet-rpc -- --rpc-bind-port 38084 --password-file ~/1/masari/wallet_pass --wallet-file ~/1/masari/pool --disable-rpc-login --trusted-daemon

